### PR TITLE
Grant jayasanka access to mota

### PR DESCRIPTION
**Pull request by jayasanka-sack**
I'm working on migrating wiki. As a part of it, I need access to the DB to run SQL query to change user emails to the new format `<username>@id.openmrs.org`.

### CODE REVIEW

**Comment by rkorytkowski** [comment]
@ibacher I don't seem to have ssh access to mota to apply this. Please apply the change for @jayasanka-sack.

**Comment by ibacher** [comment]
Surely we don't want to _remove_ @jayasanka-sack from adaba, right?

**Comment by jayasanka-sack** [comment]
I no longer use that key pair. The one I added to mota is a new public key. I didn't update adaba thinking I no longer need access to it.

**Comment by ibacher** [comment]
@jayasanka-sack I don't see why we wouldn't want you to retain access.

**Comment by jayasanka-sack** [comment]
I should ssh with ` ssh jayasanka@mota.openmrs.org`, right?

it says`jayasanka@mota.openmrs.org: Permission denied (publickey).` I'll drop you a message via slack. 

> @jayasanka-sack I don't see why we wouldn't want you to retain access.

Sure, I'll send another PR.

**Comment by jayasanka-sack** [comment]
@ibacher It works. Thanks!

**Pull request merged**
